server:
  port: 9022
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiecheng1211/tensquare.git
  application:
    name: tensquare-config
  rabbitmq:
    host: 192.168.157.129
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
