server:
  port: 9005
spring:
  application:
    name: tensquare-gather
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.157.128:3306/tensquare_gathering?characterEncoding=utf-8
    username: root
    password: 1234
  jpa:
    show-sql: true