spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      uri: mongodb://192.168.157.128:27017
      database: spitdb
    redis:
      port: 6379
      host: 192.168.157.128
server:
  port: 9007