server:
  port: 9002
spring:
  application:
    name: tensquare-recruit
  jpa:
    database: mysql
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.157.128:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: 1234
