spring:
  application:
    name: tensquare-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.157.128:3306/tensquare_article?characterEncoding=utf-8
    password: 1234
    username: root
  redis:
    port: 6379
    host: 192.168.157.128
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9004
